spring:
  application:
    name: gateway-router
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://minidooray
          predicates:
            - Path=/api/accounts/**

        - id: task-service
          uri: lb://Mini-Dooray-8-task
          predicates:
            - Path=/api/projects/**

server:
  port: 8078

eureka-server:
  host: localhost
  port: 8079

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:1234@${eureka-server.host}:${eureka-server.port}/eureka
#      defaultZone: http://eureka:8079/eureka

---
spring:
  config:
    activate:
      on-active: docker-eureka

eureka-server:
  host: eureka
  port: 8079